spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DATA_SOURCE_DRIVER}
  jpa:
    properties:
      hibernate:
        dialect: ${DB_JPA_DIALECT}
    hibernate:
      ddl-auto: ${DB_JPA_DDL_AUTO}
mail:
  host: ${MAIL_HOST}
  user: ${MAIL_USER}
  password: ${MAIL_PASSWORD}
  port: ${MAIL_PORT}
  from: ${MAIL_FROM}
info:
  application:
    name: Clients API
    description: Simple API providing CRUD operations for Client domain
    author:
      name: Renan Silva
      bio: Avid and curious learner